# Loaded by pt_control when ros2_control_hardware_type:=mujoco, with the selected camera's mujoco_camera_<camera>.yaml.
/**:
  ros__parameters:
    mujoco_plugins:
      mujoco_camera_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 30.0
      # Simulated /emergency_stop
      emergency_stop_plugin:
        type: "mujoco_ros2_plugins/EmergencyStopPlugin"
